# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Lets Blogg It
tagline:          'A Blog for GSOC and beyond'
description:      'This blog was created with primarly objective being, publishing my GSOC work. I was not the "blogging" type untill now. Well who knows where we will end up from here. '
url:              http://pasindubawantha.github.io
baseurl:          /

author:
  name:           'Pasindu Perera'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:          https://github.com/pasindubawantha
