# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Lets Blog It
tagline:          'Blogging for the sake of it'
description:      "What can I say, it's a blog."
url:              https://pasindubawantha.github.io/about
baseurl:          /

author:
  name:           'Pasindu Perera'
  url:            https://twitter.com/mdo

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pasindubawantha
