# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Lets Blogg It
tagline:          'A Blog for GSOC'
description:      "What can I say it's a blog, check <a href='https://pasindubawantha.github.io/about' target='_blank'>About</a> page for details."
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Pasindu Perera'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pasindubawantha
