# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Lets Blogg It
tagline:          'A Blog for GSOC and beyond'
description:      'Well it's a blog what can I say. check the <a href="http://pasindubawantha.github.io/about" target="_blank">About</a> page for more details'
url:              http://pasindubawantha.github.io
baseurl:          /

author:
  name:           'Pasindu Perera'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:          https://github.com/pasindubawantha
